let  card = [
  {
    id: "1",
    name: "Название товара длинное в две строки наверное",
    dimensions: "12.3 x 14.6 x 4.3 м",
    area: "33 м²",
    capacity: "15 чел.",
    warranty: "10 лет",
    price_original: "6127500₽",
    discount: "25%",
    price_discounted: "5023900₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
  {
    id: "2",
    name: "Название товара длинное в две строки наверное",
    dimensions: "10.0 x 12.0 x 3.5 м",
    area: "28 м²",
    capacity: "12 чел.",
    warranty: "8 лет",
    price_original: "5120000₽",
    discount: "20%",
    price_discounted: "4096000₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
  {
    id: "3",
    name: "Название товара длинное в две строки наверное",
    dimensions: "14.0 x 16.0 x 5.0 м",
    area: "40 м²",
    capacity: "20 чел.",
    warranty: "12 лет",
    price_original: "8120000₽",
    discount: "30%",
    price_discounted: "5684000₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
  {
    id: "4",
    name: "Название товара длинное в две строки наверное",
    dimensions: "11.5 x 13.0 x 4.0 м",
    area: "30 м²",
    capacity: "14 чел.",
    warranty: "9 лет",
    price_original: "5225000₽",
    discount: "15%",
    price_discounted: "4441250₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
  {
    id: "5",
    name: "Название товара длинное в две строки наверное",
    dimensions: "9.0 x 11.0 x 3.0 м",
    area: "25 м²",
    capacity: "10 чел.",
    warranty: "7 лет",
    price_original: "4220000₽",
    discount: "10%",
    price_discounted: "3798000₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
  {
    id: "6",
    name: "Название товара длинное в две строки наверное",
    dimensions: "13.0 x 15.0 x 4.5 м",
    area: "35 м²",
    capacity: "16 чел.",
    warranty: "10 лет",
    price_original: "7120000₽",
    discount: "20%",
    price_discounted: "5696000₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
  {
    id: "7",
    name: "Название товара длинное в две строки наверное",
    dimensions: "8.5 x 10.0 x 3.5 м",
    area: "20 м²",
    capacity: "8 чел.",
    warranty: "5 лет",
    price_original: "3520000₽",
    discount: "5%",
    price_discounted: "3344000₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
  {
    id: "8",
    name: "Название товара длинное в две строки наверное",
    dimensions: "15.0 x 17.0 x 5.5 м",
    area: "45 м²",
    capacity: "22 чел.",
    warranty: "15 лет",
    price_original: "9120000₽",
    discount: "25%",
    price_discounted: "6840000₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
  {
    id: "9",
    name: "Название товара длинное в две строки наверное",
    dimensions: "12.0 x 14.0 x 4.0 м",
    area: "32 м²",
    capacity: "14 чел.",
    warranty: "10 лет",
    price_original: "6020000₽",
    discount: "18%",
    price_discounted: "4936400₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
  {
    id: "10",
    name: "Название товара длинное в две строки наверное",
    dimensions: "10.5 x 12.5 x 3.5 м",
    area: "26 м²",
    capacity: "11 чел.",
    warranty: "8 лет",
    price_original: "4820000₽",
    discount: "12%",
    price_discounted: "4241600₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
  {
    id: "11",
    name: "Название товара длинное в две строки наверное",
    dimensions: "13.5 x 15.5 x 4.8 м",
    area: "38 м²",
    capacity: "18 чел.",
    warranty: "12 лет",
    price_original: "7620000₽",
    discount: "22%",
    price_discounted: "5943600₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
  {
    id: "12",
    name: "Название товара длинное в две строки наверное",
    dimensions: "9.5 x 11.5 x 3.2 м",
    area: "24 м²",
    capacity: "9 чел.",
    warranty: "6 лет",
    price_original: "4020000₽",
    discount: "8%",
    price_discounted: "3698400₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
  {
    id: "13",
    name: "Название товара длинное в две строки наверное",
    dimensions: "11.0 x 13.0 x 4.0 м",
    area: "30 м²",
    capacity: "13 чел.",
    warranty: "9 лет",
    price_original: "5320000₽",
    discount: "14%",
    price_discounted: "4575200₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
  {
    id: "14",
    name: "Название товара длинное в две строки наверное",
    dimensions: "10.0 x 12.0 x 3.5 м",
    area: "28 м²",
    capacity: "12 чел.",
    warranty: "8 лет",
    price_original: "4820000₽",
    discount: "10%",
    price_discounted: "4338000₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
  {
    id: "15",
    name: "Название товара длинное в две строки наверное",
    dimensions: "14.5 x 16.5 x 5.0 м",
    area: "42 м²",
    capacity: "21 чел.",
    warranty: "11 лет",
    price_original: "8220000₽",
    discount: "25%",
    price_discounted: "6165000₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
  {
    id: "16",
    name: "Название товара длинное в две строки наверное",
    dimensions: "13.0 x 15.0 x 4.5 м",
    area: "36 м²",
    capacity: "17 чел.",
    warranty: "10 лет",
    price_original: "7120000₽",
    discount: "18%",
    price_discounted: "5838400₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
  {
    id: "17",
    name: "Название товара длинное в две строки наверное",
    dimensions: "12.5 x 14.5 x 4.0 м",
    area: "34 м²",
    capacity: "16 чел.",
    warranty: "10 лет",
    price_original: "6420000₽",
    discount: "15%",
    price_discounted: "5457000₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
  {
    id: "18",
    name: "Название товара длинное в две строки наверное",
    dimensions: "10.5 x 12.5 x 3.8 м",
    area: "27 м²",
    capacity: "11 чел.",
    warranty: "7 лет",
    price_original: "4820000₽",
    discount: "10%",
    price_discounted: "4338000₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
  {
    id: "19",
    name: "Название товара длинное в две строки наверное",
    dimensions: "15.0 x 17.0 x 5.0 м",
    area: "45 м²",
    capacity: "22 чел.",
    warranty: "15 лет",
    price_original: "9120000₽",
    discount: "30%",
    price_discounted: "6384000₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
  {
    id: "20",
    name: "Название товара длинное в две строки наверное",
    dimensions: "11.0 x 13.0 x 4.0 м",
    area: "30 м²",
    capacity: "13 чел.",
    warranty: "8 лет",
    price_original: "5220000₽",
    discount: "15%",
    price_discounted: "4437000₽",
    image:  "../../assets/img/cards.png",
    buy_action: "Купить",
  },
];
export default card
